### ISSUE TITLE
Wireframy

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/redflags.slovensko.digital#18]
Spravit wireframy na podstranky

**Comment by eronisko** [comment]
@jsuchal budes toto robit ty alebo mam zobrat ja?

**Comment by jsuchal** [comment]
V klude zober a pytaj sa.

**Comment by eronisko** [comment]
Prva verzia: https://www.figma.com/proto/M2EVlyjfS9HmLltC0NZ06nMr/Red-Flags-Wireframes?scaling=min-zoom&redirected=1&node-id=1%3A104
