### ISSUE TITLE
Kategorizacia projektov

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/redflags.slovensko.digital#46]
Projekty nebudeme automaticky hodnotit (aspon navonok) ale potrebujeme ich zaradit do dvoch (resp troch) kategorii.

kategoria Zle projekty: (zrele na zrusenie, vyrazne prepracovanie)
kategoria Dobre projekty: (mozu ist dalej)
kategoria nuda/nevedena. 

Tieto dve kategorie budu na hlavnej stranke (top 5), potom na podstranke projektov potrebujeme to rozlisit (farebne asi)

V adminovi si predstavujem, ze proste k projektu bude nejaky prepinac na dobry/zly/nuda

**Comment by pavolzbell** [comment]
@jsuchal zatial administracna cast je poriesena tu https://github.com/slovensko-digital/redflags.slovensko.digital/pull/50
