### ISSUE TITLE
Ako admin chcem vidiet draft podstranky pre publikaciu

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/redflags.slovensko.digital#5]
kliknem v adminovi na stranku/projekt a chcem vidiet *ako by to vyzeralo keby som to teraz publikoval*.

**Comment by jsuchal** [comment]
@pavolzbell toto by som potreboval na ladenie, vies to kuknut?

**Comment by pavolzbell** [comment]
@jsuchal pozriem na to teraz
